
beta_prediction_writer_callback:
  _target_: src.callbacks.BetaPredictionWriterCallback
  save_path: "/groups/icecube/moust/work/IceCubeEncoderTransformer/prediction/beta_predictions.csv" 
  #${paths:output}$/beta_predictions.csv