defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - beta_prediction_writer_callback.yaml
  - attention_weight_writer_callback.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss" #"val/loss" #"val/acc"
  mode: "min" #"min" #"max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor:  "val/loss" #"val/acc"
  patience: 3
  mode: "min" #"max" "min"

beta_prediction_writer_callback:
  save_path: ${paths.output_dir}/beta_predictions.csv

attention_weight_writer_callback:
  save_path: ${paths.output_dir}/attention_weights.db

model_summary:
  max_depth: -1
